# Generated by Django 4.2.5 on 2023-11-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painters', '0004_alter_message_options_alter_painter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painter',
            options={'ordering': ['name']},
        ),
    ]
